module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  corePlugins: { preflight: true },
  theme: {
    extend: {
      colors: {
        absoluteblack: "var(--absoluteblack)",
        absolutewhite: "var(--absolutewhite)",
        "dark-03": "var(--dark-03)",
        "dark-06": "var(--dark-06)",
        "dark-08": "var(--dark-08)",
        "dark-12": "var(--dark-12)",
        "dark-15": "var(--dark-15)",
        "dark-20": "var(--dark-20)",
        "dark-25": "var(--dark-25)",
        "dark-30": "var(--dark-30)",
        "grey-40": "var(--grey-40)",
        "grey-50": "var(--grey-50)",
        "grey-70": "var(--grey-70)",
        "grey-80": "var(--grey-80)",
        "grey-90": "var(--grey-90)",
        "grey-95": "var(--grey-95)",
        "grey-97": "var(--grey-97)",
        "grey-99": "var(--grey-99)",
        "purple-55": "var(--purple-55)",
        "purple-60": "var(--purple-60)",
        "purple-70": "var(--purple-70)",
        "purple-80": "var(--purple-80)",
        "purple-90": "var(--purple-90)",
        "purple-95": "var(--purple-95)",
        "purple-97": "var(--purple-97)",
        "purple-99": "var(--purple-99)",
      },
    },
  },
  plugins: [],
};
